// Generated by CoffeeScript 1.6.2
var getWorksXML, init, parseXml, randomizeAboutPic, randomizeHeaderPic;

getWorksXML = function() {
  return $.ajax({
    type: "GET",
    url: "works.xml",
    dataType: "xml",
    success: parseXml
  });
};

parseXml = function(data) {
  return $(data).find("project").each(function() {
    var pBlurb, pCat, pImage, pLink, pTitle, projectHtml;

    pCat = "<h4>" + ($(this).find("category").text()) + "</h4>";
    pTitle = "<h2>" + ($(this).find("title").text()) + "</h2>";
    pImage = "<img src='" + ($(this).find("image").text()) + "'/>";
    pBlurb = "<p>" + ($(this).find("blurb").text()) + "</p>";
    pLink = "<a href='" + ($(this).find("link").text()) + "' target='_blank'>";
    projectHtml = "<div class='project'>" + pCat + pTitle + pBlurb + pLink + pImage + "</a></div>";
    return $("#content").append(projectHtml);
  });
};

randomizeAboutPic = function() {
  var randomNumber;

  randomNumber = Math.floor(Math.random() * 4) + 1;
  return $("#about").css('background-image', "url(images/BobbyHead" + randomNumber + ".png)");
};

randomizeHeaderPic = function() {
  var randomNumber;

  randomNumber = Math.floor(Math.random() * 4) + 1;
  return $("#header").css('background-image', "url(images/bg-head" + randomNumber + ".png)");
};

init = function() {
  setTimeout((function() {
    window.scrollTo(0, 1);
  }), 100);
  getWorksXML();
  randomizeAboutPic();
  return randomizeHeaderPic();
};

$(document).ready(init());

/*
//@ sourceMappingURL=main.map
*/
