// Generated by CoffeeScript 1.7.1
var getWorksXML, init, links, onClick, onMouseOut, onMouseOver, parseXml, randomizeAboutPic, randomizeAboutQuote, randomizeHeaderPic;

links = [];

getWorksXML = function() {
  return $.ajax({
    type: "GET",
    url: "works.xml",
    dataType: "xml",
    success: parseXml
  });
};

parseXml = function(data) {
  return $(data).find("project").each(function(i, item) {
    var pBlurb, pCat, pTitle, projectHtml;
    links.push($(this).find("link").text());
    pCat = "<h4>" + ($(this).find("category").text()) + "</h4>";
    pTitle = "<h2>" + ($(this).find("title").text()) + "</h2>";
    pBlurb = "<p>" + ($(this).find("blurb").text()) + "</p>";
    projectHtml = "<div class='project' id='" + i + "'> " + pTitle + " " + pCat + " " + pBlurb + "</div>";
    return $("#content").append(projectHtml);
  });
};

randomizeAboutPic = function() {
  var random_number;
  random_number = Math.floor(Math.random() * 3) + 2;
  return $("#about").css('background-image', "url(images/BobbyHead" + random_number + ".png)");
};

randomizeHeaderPic = function() {
  var random_number;
  random_number = Math.floor(Math.random() * 5);
  return $("#header").css('background-image', "url(images/bg-head" + random_number + ".png)");
};

randomizeAboutQuote = function() {
  var quotes, random_number;
  quotes = ["He also enjoys Aikido, Jaco Pastorius & trips to Iceland.", "He also enjoys biking, Igor Stravinsky & travel to Thailand.", "He also enjoys bass guitar, kale salads & exploring Bermuda.", "He also enjoys jazz harmonies, mojitos & trips to Hawaii.", "He also enjoys Paul Klee, Matrix Math & touring the Czech Republic."];
  random_number = Math.floor(Math.random() * 5);
  return $(".quote").text(quotes[random_number]);
};

init = function() {
  setTimeout((function() {
    window.scrollTo(0, 1);
  }), 100);
  getWorksXML();
  randomizeAboutPic();
  return randomizeAboutQuote();
};

onMouseOver = function(evt) {
  if (evt.target.classList.contains('project')) {
    return evt.target.classList.add('hot');
  }
};

onMouseOut = function(evt) {
  if (evt.target.classList.contains('project')) {
    return evt.target.classList.remove('hot');
  }
};

onClick = function(evt) {
  if (evt.target.classList.contains('project')) {
    return window.location = links[+evt.target.id];
  }
};

$(document).ready(init());

document.body.addEventListener('mouseover', onMouseOver);

document.body.addEventListener('mouseout', onMouseOut);

document.body.addEventListener('click', onClick);

/*
//@ sourceMappingURL=main.map
*/
