// Generated by CoffeeScript 1.6.2
var getWorksXML, init, parseXml, randomizeAboutPic, randomizeAboutQuote, randomizeHeaderPic;

getWorksXML = function() {
  return $.ajax({
    type: "GET",
    url: "works.xml",
    dataType: "xml",
    success: parseXml
  });
};

parseXml = function(data) {
  return $(data).find("project").each(function() {
    var pBlurb, pCat, pImage, pLink, pTitle, projectHtml;

    pCat = "<h4>" + ($(this).find("category").text()) + "</h4>";
    pTitle = "<h2>" + ($(this).find("title").text()) + "</h2>";
    pImage = "<img src='" + ($(this).find("image").text()) + "'/>";
    pBlurb = "<p>" + ($(this).find("blurb").text()) + "</p>";
    pLink = "<a href='" + ($(this).find("link").text()) + "' target='_blank'>";
    projectHtml = "<div class='project'> " + pCat + " " + pTitle + " " + pBlurb + " " + pLink + " " + pImage + "</a></div>";
    return $("#content").append(projectHtml);
  });
};

randomizeAboutPic = function() {
  var random_number;

  random_number = Math.floor(Math.random() * 5);
  return $("#about").css('background-image', "url(images/BobbyHead" + random_number + ".png)");
};

randomizeHeaderPic = function() {
  var random_number;

  random_number = Math.floor(Math.random() * 5);
  return $("#header").css('background-image', "url(images/bg-head" + random_number + ".png)");
};

randomizeAboutQuote = function() {
  var quotes, random_number;

  quotes = ["He also enjoys Aikido, Jaco Pastorius & trips to Iceland.", "He also enjoys biking, Igor Stravinsky & travel to Thailand.", "He also enjoys bass guitar, kale salads & exploring Bermuda.", "He also enjoys jazz harmonies, mojitos & trips to Hawaii.", "He also enjoys Paul Klee, Matrix Math & touring the Czech Republic."];
  random_number = Math.floor(Math.random() * 5);
  return $(".quote").text(quotes[random_number]);
};

init = function() {
  setTimeout((function() {
    window.scrollTo(0, 1);
  }), 100);
  getWorksXML();
  randomizeAboutPic();
  randomizeHeaderPic();
  return randomizeAboutQuote();
};

$(document).ready(init());

/*
//@ sourceMappingURL=main.map
*/
